// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editor': string;
  'properties': string;
}
export const cssExports: CssExports;
export default cssExports;
