// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'container': string;
  'label': string;
  'tab': string;
}
export const cssExports: CssExports;
export default cssExports;
