// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'borderless': string;
  'container': string;
  'label': string;
  'panel': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
